security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        mysql:
            entity:
                class: App\Entity\User
                property: userName
          
    encoders:
        App\Entity\User:
            algorithm: bcrypt             
            encode_as_base64: false
            iterations: 13
    firewalls:
        
        main:
            anonymous: true
            pattern: ^/
            form_login:
                login_path: login           
                
                check_path: login           
                default_target_path: home
              
            provider: mysql         
            
            logout:
                path:   /logout         
                target: /               
                
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER           
        
    access_control:   
        - { path: ^/perso, roles: ROLE_ADMIN}
        - { path: ^/visiteur, roles: ROLE_USER}

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
